name: Fetch M3U Playlist

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch M3U File
        run: |
          curl -L "https://voot.vodep39240327.workers.dev/?voot.m3u" -o channels.m3u

      - name: Clean M3U (Optional Security)
        run: |
          sed -i 's/http:/https:/g' channels.m3u

      - name: Commit & Push
        run: |
          git config --global user.name "m3u-bot"
          git config --global user.email "bot@users.noreply.github.com"
          
          git add channels.m3u
          git commit -m "Auto update M3U" || echo "No changes"
          git push
